import Sidebar from "./ components/Sidebar";
import { WalletContextProvider } from "./context/context";
import "./globals.css";

export const metadata = {
  title: "Evmos Wallet",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <WalletContextProvider>
          <div className="flex container mx-auto">
            <Sidebar />

            <div className="flex-1 p-3">{children}</div>
          </div>
        </WalletContextProvider>
      </body>
    </html>
  );
}
